#!/usr/bin/env python3
"""Turn the backend brand marks into Android and desktop assets.

`tools/icons/brand-svg/` is the single source for the three backends Mozz can
talk to, exactly as `tabler-svg/` is for the interface icons. iOS reads those
SVGs directly out of `Brands.xcassets`; Android and Avalonia cannot, so this
transcribes them:

  * `clients/android/app/src/main/res/drawable/brand_*.xml` — VectorDrawables,
    drawn with a solid fill so Compose can tint them like any other icon.
  * `clients/desktop/Assets/BrandIcons.axaml` — StreamGeometry resources, kept
    apart from the generated `Icons.axaml` because those are Tabler's and carry
    Tabler's licence note. These are the products' own marks.

The marks are filled shapes on a 24x24 canvas — unlike the Tabler icons, which
are 2pt strokes — so neither output carries a stroke, and the Navidrome mark
needs `evenOdd` to keep the holes in the record.

Usage: tools/icons/build-brand-icons.py
"""

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/icons/brand-svg"
ANDROID = ROOT / "clients/android/app/src/main/res/drawable"
DESKTOP = ROOT / "clients/desktop/Assets/BrandIcons.axaml"

# Mozz's own names for the three, and the resource names they get. The Subsonic
# row is drawn with Navidrome's mark because Subsonic is a protocol with no mark
# of its own and Navidrome is what nearly everyone speaking it is running; the
# row says "Navidrome (Subsonic)" so the label carries the accuracy.
BRANDS = [
    ("plex", "Plex"),
    ("jellyfin", "Jellyfin"),
    ("navidrome", "Navidrome"),
]


def read(name: str) -> tuple[str, bool]:
    """The mark's single path, and whether it needs the even-odd fill rule."""
    svg = (SOURCE / f"{name}.svg").read_text()
    paths = re.findall(r'\sd="([^"]+)"', svg)
    if len(paths) != 1:
        sys.exit(f"{name}.svg: expected one path, found {len(paths)}")
    return paths[0], 'fill-rule="evenodd"' in svg


def write_android(name: str, title: str, data: str, even_odd: bool) -> None:
    fill_type = '\n        android:fillType="evenOdd"' if even_odd else ""
    (ANDROID / f"brand_{name}.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- {title}'s own mark. Generated from tools/icons/brand-svg/{name}.svg\n"
        "     by tools/icons/build-brand-icons.py. Do not edit by hand. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="24"\n'
        '    android:viewportHeight="24">\n'
        "    <path\n"
        '        android:fillColor="#FF000000"'
        f"{fill_type}\n"
        f'        android:pathData="{data}" />\n'
        "</vector>\n"
    )


def write_desktop(entries: list[tuple[str, str, str, bool]]) -> None:
    lines = [
        "<!--",
        "  GENERATED by tools/icons/build-brand-icons.py from tools/icons/brand-svg/*.svg.",
        "  Do not edit by hand.",
        "",
        "  Separate from Icons.axaml on purpose: those are Tabler's, under Tabler's",
        "  licence. These are the three backends' own marks, and they are filled",
        "  shapes rather than 2pt strokes, so they are drawn differently too.",
        "-->",
        '<ResourceDictionary xmlns="https://github.com/avaloniaui"',
        '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    ]
    for name, title, data, even_odd in entries:
        # F1 is Avalonia's nonzero flag; its absence is even-odd, which is the
        # default and so is written as nothing at all.
        prefix = "" if even_odd else "F1 "
        key = f"IconBrand{title}"
        lines.append(f'    <StreamGeometry x:Key="{key}">{prefix}{data}</StreamGeometry>')
    lines.append("</ResourceDictionary>")
    DESKTOP.write_text("\n".join(lines) + "\n")


def main() -> None:
    entries = []
    for name, title in BRANDS:
        data, even_odd = read(name)
        write_android(name, title, data, even_odd)
        entries.append((name, title, data, even_odd))
    write_desktop(entries)
    print(f"wrote {len(entries)} brand marks to Android and desktop")


if __name__ == "__main__":
    main()
